-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- 主機： 127.0.0.1
-- 產生時間： 2020-08-06 19:42:16
-- 伺服器版本： 10.4.11-MariaDB
-- PHP 版本： 7.2.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- 資料庫： `eeweb`
--

-- --------------------------------------------------------

--
-- 資料表結構 `template`
--

CREATE TABLE `template` (
  `tID` tinyint(2) UNSIGNED ZEROFILL NOT NULL,
  `tName` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `type` tinyint(2) NOT NULL,
  `pages` tinyint(2) DEFAULT 1,
  `begin` varchar(2000) COLLATE utf8_unicode_ci NOT NULL,
  `end` varchar(500) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- 傾印資料表的資料 `template`
--

INSERT INTO `template` (`tID`, `tName`, `type`, `pages`, `begin`, `end`) VALUES
(01, 'antique', 1, 6, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Document</title>\r\n</head>', '</html>'),
(04, 'agency', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n    <head>\r\n        <meta charset=\"utf-8\" />\r\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n        <meta name=\"description\" content=\"\" />\r\n        <meta name=\"author\" content=\"\" />\r\n        <title>Agency - Start Bootstrap Theme</title>\r\n        <link rel=\"icon\" type=\"image/x-icon\" href=\"/templated/agency/assets/img/favicon.ico\" />\r\n        <!-- Font Awesome icons (free version)-->\r\n        <script src=\"https://use.fontawesome.com/releases/v5.13.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n        <!-- Google fonts-->\r\n        <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n        <link href=\"https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\" />\r\n        <link href=\"https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n        <!-- Core theme CSS (includes Bootstrap)-->\r\n        <link href=\"/templated/agency/css/styles.css\" rel=\"stylesheet\" />\r\n    </head>', '</html>'),
(05, 'blog', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"author\" content=\"\">\r\n\r\n  <title>Clean Blog - Start Bootstrap Theme</title>\r\n\r\n  <!-- Bootstrap core CSS -->\r\n  <link href=\"/templated/blog/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom fonts for this template -->\r\n  <link href=\"/templated/blog/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n  <link href=\'https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic\' rel=\'stylesheet\' type=\'text/css\'>\r\n  <link href=\'https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800\' rel=\'stylesheet\' type=\'text/css\'>\r\n\r\n  <!-- Custom styles for this template -->\r\n  <link href=\"/templated/blog/css/clean-blog.min.css\" rel=\"stylesheet\">\r\n\r\n</head>', '</html>'),
(06, 'casual', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"author\" content=\"\">\r\n\r\n  <title>Business Casual - Start Bootstrap Theme</title>\r\n\r\n  <!-- Bootstrap core CSS -->\r\n  <link href=\"/templated/casual/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom fonts for this template -->\r\n  <link href=\"https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\">\r\n  <link href=\"https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom styles for this template -->\r\n  <link href=\"/templated/casual/css/business-casual.min.css\" rel=\"stylesheet\">\r\n\r\n</head>', '</html>'),
(07, 'frontpage', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"author\" content=\"\">\r\n\r\n  <title>Business Frontpage - Start Bootstrap Template</title>\r\n\r\n  <!-- Bootstrap core CSS -->\r\n  <link href=\"/templated/frontpage/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom styles for this template -->\r\n  <link href=\"/templated/frontpagecss/business-frontpage.css\" rel=\"stylesheet\">\r\n\r\n</head>\r\n', '</html>'),
(08, 'grayscale', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n    <head>\r\n        <meta charset=\"utf-8\" />\r\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n        <meta name=\"description\" content=\"\" />\r\n        <meta name=\"author\" content=\"\" />\r\n        <title>Grayscale - Start Bootstrap Theme</title>\r\n        <link rel=\"icon\" type=\"image/x-icon\" href=\"/tempalted/grayscale/assets/img/favicon.ico\" />\r\n        <!-- Font Awesome icons (free version)-->\r\n        <script src=\"https://use.fontawesome.com/releases/v5.13.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n        <!-- Google fonts-->\r\n        <link href=\"https://fonts.googleapis.com/css?family=Varela+Round\" rel=\"stylesheet\" />\r\n        <link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\" />\r\n        <!-- Core theme CSS (includes Bootstrap)-->\r\n        <link href=\"/tempalted/grayscale/css/styles.css\" rel=\"stylesheet\" />\r\n    </head>', '</html>\r\n'),
(09, 'heroic', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"author\" content=\"\">\r\n\r\n  <title>Heroic Features - Start Bootstrap Template</title>\r\n\r\n  <!-- Bootstrap core CSS -->\r\n  <link href=\"/templated/heroic/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom styles for this template -->\r\n  <link href=\"/templated/heroic/css/heroic-features.css\" rel=\"stylesheet\">\r\n\r\n</head>', '</html>\r\n'),
(10, 'pics', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"author\" content=\"\">\r\n\r\n  <title>Full Width Pics - Start Bootstrap Template</title>\r\n\r\n  <!-- Bootstrap core CSS -->\r\n  <link href=\"/templated/pics/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom styles for this template -->\r\n  <link href=\"/templated/pics/css/full-width-pics.css\" rel=\"stylesheet\">\r\n\r\n</head>', '</html>\r\n'),
(11, 'resume', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n    <head>\r\n        <meta charset=\"utf-8\" />\r\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n        <meta name=\"description\" content=\"\" />\r\n        <meta name=\"author\" content=\"\" />\r\n        <title>Resume - Start Bootstrap Theme</title>\r\n        <link rel=\"icon\" type=\"image/x-icon\" href=\"/templated/resume/assets/img/favicon.ico\" />\r\n        <!-- Font Awesome icons (free version)-->\r\n        <script src=\"https://use.fontawesome.com/releases/v5.13.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n        <!-- Google fonts-->\r\n        <link href=\"https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n        <link href=\"https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i\" rel=\"stylesheet\" type=\"text/css\" />\r\n        <!-- Core theme CSS (includes Bootstrap)-->\r\n        <link href=\"/templated/resume/css/styles.css\" rel=\"stylesheet\" />\r\n    </head>', '</html>\r\n'),
(12, 'small', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"author\" content=\"\">\r\n\r\n  <title>Small Business - Start Bootstrap Template</title>\r\n\r\n  <!-- Bootstrap core CSS -->\r\n  <link href=\"/templated/small/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom styles for this template -->\r\n  <link href=\"/templated/small/css/small-business.css\" rel=\"stylesheet\">\r\n\r\n</head>', '</html>\r\n'),
(13, 'wonder', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"author\" content=\"\">\r\n\r\n  <title>One Page Wonder - Start Bootstrap Template</title>\r\n\r\n  <!-- Bootstrap core CSS -->\r\n  <link href=\"/templated/wonder/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom fonts for this template -->\r\n  <link href=\"https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900\" rel=\"stylesheet\">\r\n  <link href=\"https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom styles for this template -->\r\n  <link href=\"/templated/wonder/css/one-page-wonder.min.css\" rel=\"stylesheet\">\r\n\r\n</head>', '</html>\r\n'),
(14, 'agency', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n    <head>\r\n        <meta charset=\"utf-8\" />\r\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n        <meta name=\"description\" content=\"\" />\r\n        <meta name=\"author\" content=\"\" />\r\n        <title>Agency - Start Bootstrap Theme</title>\r\n        <link rel=\"icon\" type=\"image/x-icon\" href=\"/templated/agency/assets/img/favicon.ico\" />\r\n        <!-- Font Awesome icons (free version)-->\r\n        <script src=\"https://use.fontawesome.com/releases/v5.13.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n        <!-- Google fonts-->\r\n        <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n        <link href=\"https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\" />\r\n        <link href=\"https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n        <!-- Core theme CSS (includes Bootstrap)-->\r\n        <link href=\"/templated/agency/css/styles.css\" rel=\"stylesheet\" />\r\n    </head>', '</html>'),
(15, 'blog', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"author\" content=\"\">\r\n\r\n  <title>Clean Blog - Start Bootstrap Theme</title>\r\n\r\n  <!-- Bootstrap core CSS -->\r\n  <link href=\"/templated/blog/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom fonts for this template -->\r\n  <link href=\"/templated/blog/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n  <link href=\'https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic\' rel=\'stylesheet\' type=\'text/css\'>\r\n  <link href=\'https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800\' rel=\'stylesheet\' type=\'text/css\'>\r\n\r\n  <!-- Custom styles for this template -->\r\n  <link href=\"/templated/blog/css/clean-blog.min.css\" rel=\"stylesheet\">\r\n\r\n</head>', '</html>'),
(16, 'casual', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"author\" content=\"\">\r\n\r\n  <title>Business Casual - Start Bootstrap Theme</title>\r\n\r\n  <!-- Bootstrap core CSS -->\r\n  <link href=\"/templated/casual/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom fonts for this template -->\r\n  <link href=\"https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\">\r\n  <link href=\"https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom styles for this template -->\r\n  <link href=\"/templated/casual/css/business-casual.min.css\" rel=\"stylesheet\">\r\n\r\n</head>', '</html>'),
(17, 'frontpage', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"author\" content=\"\">\r\n\r\n  <title>Business Frontpage - Start Bootstrap Template</title>\r\n\r\n  <!-- Bootstrap core CSS -->\r\n  <link href=\"/templated/frontpage/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom styles for this template -->\r\n  <link href=\"/templated/frontpagecss/business-frontpage.css\" rel=\"stylesheet\">\r\n\r\n</head>\r\n', '</html>'),
(18, 'grayscale', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n    <head>\r\n        <meta charset=\"utf-8\" />\r\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n        <meta name=\"description\" content=\"\" />\r\n        <meta name=\"author\" content=\"\" />\r\n        <title>Grayscale - Start Bootstrap Theme</title>\r\n        <link rel=\"icon\" type=\"image/x-icon\" href=\"/tempalted/grayscale/assets/img/favicon.ico\" />\r\n        <!-- Font Awesome icons (free version)-->\r\n        <script src=\"https://use.fontawesome.com/releases/v5.13.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n        <!-- Google fonts-->\r\n        <link href=\"https://fonts.googleapis.com/css?family=Varela+Round\" rel=\"stylesheet\" />\r\n        <link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\" />\r\n        <!-- Core theme CSS (includes Bootstrap)-->\r\n        <link href=\"/tempalted/grayscale/css/styles.css\" rel=\"stylesheet\" />\r\n    </head>', '</html>\r\n'),
(19, 'heroic', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"author\" content=\"\">\r\n\r\n  <title>Heroic Features - Start Bootstrap Template</title>\r\n\r\n  <!-- Bootstrap core CSS -->\r\n  <link href=\"/templated/heroic/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom styles for this template -->\r\n  <link href=\"/templated/heroic/css/heroic-features.css\" rel=\"stylesheet\">\r\n\r\n</head>', '</html>\r\n'),
(20, 'pics', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"author\" content=\"\">\r\n\r\n  <title>Full Width Pics - Start Bootstrap Template</title>\r\n\r\n  <!-- Bootstrap core CSS -->\r\n  <link href=\"/templated/pics/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom styles for this template -->\r\n  <link href=\"/templated/pics/css/full-width-pics.css\" rel=\"stylesheet\">\r\n\r\n</head>', '</html>\r\n'),
(21, 'resume', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n    <head>\r\n        <meta charset=\"utf-8\" />\r\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n        <meta name=\"description\" content=\"\" />\r\n        <meta name=\"author\" content=\"\" />\r\n        <title>Resume - Start Bootstrap Theme</title>\r\n        <link rel=\"icon\" type=\"image/x-icon\" href=\"/templated/resume/assets/img/favicon.ico\" />\r\n        <!-- Font Awesome icons (free version)-->\r\n        <script src=\"https://use.fontawesome.com/releases/v5.13.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n        <!-- Google fonts-->\r\n        <link href=\"https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n        <link href=\"https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i\" rel=\"stylesheet\" type=\"text/css\" />\r\n        <!-- Core theme CSS (includes Bootstrap)-->\r\n        <link href=\"/templated/resume/css/styles.css\" rel=\"stylesheet\" />\r\n    </head>', '</html>\r\n'),
(22, 'small', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"author\" content=\"\">\r\n\r\n  <title>Small Business - Start Bootstrap Template</title>\r\n\r\n  <!-- Bootstrap core CSS -->\r\n  <link href=\"/templated/small/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom styles for this template -->\r\n  <link href=\"/templated/small/css/small-business.css\" rel=\"stylesheet\">\r\n\r\n</head>', '</html>\r\n'),
(23, 'wonder', 1, 1, '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n<head>\r\n\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"author\" content=\"\">\r\n\r\n  <title>One Page Wonder - Start Bootstrap Template</title>\r\n\r\n  <!-- Bootstrap core CSS -->\r\n  <link href=\"/templated/wonder/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom fonts for this template -->\r\n  <link href=\"https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900\" rel=\"stylesheet\">\r\n  <link href=\"https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i\" rel=\"stylesheet\">\r\n\r\n  <!-- Custom styles for this template -->\r\n  <link href=\"/templated/wonder/css/one-page-wonder.min.css\" rel=\"stylesheet\">\r\n\r\n</head>', '</html>\r\n');

--
-- 已傾印資料表的索引
--

--
-- 資料表索引 `template`
--
ALTER TABLE `template`
  ADD PRIMARY KEY (`tID`);

--
-- 在傾印的資料表使用自動遞增(AUTO_INCREMENT)
--

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `template`
--
ALTER TABLE `template`
  MODIFY `tID` tinyint(2) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=24;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
